matrix:
  include:
    - language: python
      python:
        - '3.5'
      install:
        - pip install pipenv coveralls
        - pipenv install --dev
      script:
        - pipenv run pytest
        - pipenv run prospector
      after_success:
        - coveralls
    - language: node_js
      node_js:
        - '6'
      before_script:
        - cd gui/static
      script:
        - npm install --dev
        - npm test
        - npm run lint
